### ISSUE TITLE
Provide instances for classes with constructor parameters

### ISSUE THREAD

**Issue by yuriisurzhykov** [Jintin/KFactory#12]
Now this library generates code only for classes without constructor parameters. It would be really helpful, if your library would generate also default parameters for classes, that have some at least primitive types.

**Comment by Jintin** [comment]
Good suggestion, but given the factory might still have a single function to create the instance for all. 
Every Class with the same type might need to have same order of parameters for easy config/parse.
I create a pr can verify the idea, feel free to take a look, try or comment at #14

**Comment by Jintin** [comment]
#14 shipped with 4.0.0, feel free to try
Thanks
